import './globals.css'
import { Oswald } from 'next/font/google'
import Image from 'next/image'
import { StateContext } from '@/Context/Statecontext'
import MenuBar from '@/lib/MenuBar'

const inter = Oswald({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
          <MenuBar/>
          {children}
        </StateContext>
      </body>
    </html>
  )
}
